language: python
python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install -e .
  - pip install pytest-mock
  - pip install pytest-cov
  - pip install coveralls

script: py.test --cov multilevelbackup --cov-report term-missing -v tests/

after_success: coveralls --verbose
